Dev
AlexM-pixel/SipmlePrimer pull request #5
Opened 2020-04-19 08:52 UTC by AlexM-pixel

2020-04-20 11:02 UTC, AinisSK requested changes

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw1/Main1Activity.java
> +        super.onStop();
Знаешь же что не обязательно их переопределять. А то он у тебя тут пустой и по сути ничего не делает

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw1/Statistic.java
> +        FragmentTransaction frTransaction = fragmentManager.beginTransaction().replace(R.id.frame_for_fragment, fragment).addToBackStack(null);
Несколько команд обычно не группируют на одной строке. Обычно в таком случае делают
someClass.doFirst()
   .doSecond()
   .soThird();

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw2/Cities.java
> +class Cities {
Класс должен называться City, он же у тебя хранит данные об одном городе, а когда ты делаешь лист из таких объектов получается список городов. Примерно такая логика

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw2/Fragment1.java
> +    public  interface Listener {
Просто Listener не пойдет имя, нужно типа какого-то экшена, который описывает что за листенер, например, OnButtonClickListener

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw2/Fragment1.java
> +                listener.idButton(0);
и что такое 0 и 1 тут. Совсем не очевидно. Если это разные действия тогда более логичным будет сделать просто два метода которые будут описывать что за действие происходит. Для этого у тебя и есть интерфейс

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw2/Main2Activity.java
> +            idPosition = savedInstanceState.getInt("1");
что такое "1" тут?

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw2/Main2Activity.java
> +        if (fm.getBackStackEntryCount()>0 && frameLayout==null) {          //если наклацал фрагментов в бэкстек и телефон повернул обратно в портретный
Вот тут вопросики у меня, не совсем понимаю твою идею что бы это делать

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw2/Main2Activity.java
> +        if (fm.getBackStackEntryCount()>0 && frameLayout==null) {          //если наклацал фрагментов в бэкстек и телефон повернул обратно в портретный
Аааа, понял. Обычно не так делается, тебе хватает лишь проверить saveInstanceState на null

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw2/Main2Activity.java
> +    public void idButton(int id) {
Опять же, имя метода - это действие, которое оно выполняет. Давай потом подумаем вместе как можно тут придумать имя метода

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw2/Main2Activity.java
> +            Fragment2 fragment2 = new Fragment2();
Так не делаем желательно сразу. Причину рассказывал, и ее надо очень хорошо знать

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw2/Main2Activity.java
> +        outState.putInt("1", idPosition);
Всегда такие значения выносятся константами в верхушку класса

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw4/Main4Activity.java
> +        PresidentsAdapter adapter = new PresidentsAdapter(presidName,presidCall,presidFoto);
Не совсем понимаю тут что происходит, у тебя есть уже список президентов, но ты его разбиваешь на три разных списка и передаешь в адаптер. Вопрос, почему не передать исходный список?

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw4/Presidents.java
> +public class Presidents {
Тут тоже в единственном числе должно быть

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw4/Presidents.java
> +            new Presidents("Ким","six minutes ago", R.drawable.kim), new Presidents("Эрдоган","two minutes ago", R.drawable.erdogan));
Кардашьян что ли?)

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw4/PresidentsAdapter.java
> +        ImageView imageView = cardView.findViewById(R.id.imageFoto);
Смотри, у нас ViewHolder нужен для того, что бы избежать затратной операции findViewById, а тут у тебя все равно вызывается каждый раз при бинде, это должно выполняться один раз в onCreateViewHolder

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/res/layout/activity_constrain.xml
> +        app:layout_constraintHorizontal_bias="0.062"
Настолько маленький биас, что я думаю можно отвязать это вью от правой стороны пэрента

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/res/layout/activity_constrain.xml
> +        app:layout_constraintHorizontal_bias="1.0"
тоже самое тут, у тебя с помощью биаса вьюха прижата к правой стороне. Для этого просто не надо указывать констрэйнт для левой стороны. И правый констрэйнт подтянет ее к правой стороне

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/res/layout/activity_constrain.xml
> +        app:layout_constraintHorizontal_bias="0.5"
это тоже в таком случае лишнее

2020-04-20 11:02 UTC, AinisSK commented on app/src/main/res/layout/activity_main3.xml
> +    <LinearLayout
Вот это непонятно для чего

2020-04-22 12:27 UTC, AlexM-pixel commented on app/src/main/java/com/example/mysympleapplication/hw1/Main1Activity.java
> +        super.onStop();
наверное  что-то делал тут , затем удалил, а метод остался

2020-04-22 12:30 UTC, AlexM-pixel commented on app/src/main/java/com/example/mysympleapplication/hw1/Statistic.java
> +        FragmentTransaction frTransaction = fragmentManager.beginTransaction().replace(R.id.frame_for_fragment, fragment).addToBackStack(null);
исправил

2020-04-22 12:31 UTC, AlexM-pixel commented on app/src/main/java/com/example/mysympleapplication/hw2/Cities.java
> +class Cities {
переименовал

2020-04-22 12:57 UTC, AlexM-pixel commented on app/src/main/java/com/example/mysympleapplication/hw2/Fragment1.java
> +                listener.idButton(0);
здесь кнопки -это айтемы из списка которые передают свою позицию в списке

2020-04-22 13:01 UTC, AlexM-pixel commented on app/src/main/java/com/example/mysympleapplication/hw4/Main4Activity.java
> +        PresidentsAdapter adapter = new PresidentsAdapter(presidName,presidCall,presidFoto);
думал так мне наглядней будет, но потом исправил)

2020-04-22 13:02 UTC, AlexM-pixel commented on app/src/main/java/com/example/mysympleapplication/hw4/PresidentsAdapter.java
> +        ImageView imageView = cardView.findViewById(R.id.imageFoto);
тут чего-то наделал)

2020-04-22 13:04 UTC, AlexM-pixel commented on app/src/main/res/layout/activity_constrain.xml
> +        app:layout_constraintHorizontal_bias="0.5"
не знаю откуда это все вылазит , я такого не писал)

2020-04-22 13:17 UTC, AlexM-pixel commented on app/src/main/java/com/example/mysympleapplication/hw2/Main2Activity.java
> +        outState.putInt("1", idPosition);
единичку быстрее, но я исправлюсь)

2020-04-22 13:29 UTC, AlexM-pixel commented on app/src/main/java/com/example/mysympleapplication/hw2/Main2Activity.java
> +            Fragment2 fragment2 = new Fragment2();
а как из кода добавить в активити фрагмент не создавая его обьекта?

2020-04-22 13:32 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw2/Main2Activity.java
> +            Fragment2 fragment2 = new Fragment2();
Это касается той же проблемы что описана вот тут.
<img width="971" alt="Screen Shot 2020-04-22 at 16 31 53" src="https://user-images.githubusercontent.com/33170586/79987990-c7d8a600-84b6-11ea-8f91-d2a4b4ad1c81.png">

2020-04-22 13:32 UTC, AinisSK commented on app/src/main/java/com/example/mysympleapplication/hw2/Main2Activity.java
> +            Fragment2 fragment2 = new Fragment2();
Опять же как я говорил тут не особо критично, но когда появятся параметры точно такого нельзя допускать)

2020-04-22 13:41 UTC, AlexM-pixel commented on app/src/main/java/com/example/mysympleapplication/hw2/Fragment1.java
> +    public  interface Listener {
переименовал

2020-04-22 13:42 UTC, AlexM-pixel commented on app/src/main/java/com/example/mysympleapplication/hw4/PresidentsAdapter.java
> +        ImageView imageView = cardView.findViewById(R.id.imageFoto);
может даже правильно получилось

2020-04-25 15:50 UTC, merged